object Form2: TForm2
  Left = 0
  Top = 0
  Caption = 'Form2'
  ClientHeight = 433
  ClientWidth = 681
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Chromium1: TChromium
    Left = 0
    Top = 0
    Width = 681
    Height = 433
    Align = alClient
    DefaultUrl = 'about:blank'
    TabOrder = 0
    ExplicitLeft = 552
    ExplicitTop = 360
    ExplicitWidth = 100
    ExplicitHeight = 41
  end
end
